"""Page definitions for firstreply.dev service & industry landing pages.

Each entry is rendered by build_blog.py into dist/<dir>/<slug>.html.
Keep copy in Golam's StoryBrand voice: reader is the hero, we're the guide.
No invented statistics, no fake clients — Diji Catering is the only real one.
"""

SERVICES = [
    {
        "slug": "ai-automation",
        "nav": "AI business automation",
        "meta_title": "AI Business Automation Services UK | Firstreply",
        "meta_desc": "Automate email, reporting, documents and internal workflows with AI on n8n. Built GDPR-first for UK and worldwide businesses — and you own everything.",
        "eyebrow": "Service · AI business automation",
        "h1": "The admin didn't grow your business. Stop doing it by hand.",
        "intro": "Every week you lose hours to work a machine should do: copying data between tools, sending the same emails, building the same reports. We wire your existing tools together with AI-powered workflows — so the busywork runs itself and you keep the judgement calls.",
        "problem": "<p>Most small businesses don't have a software problem — they have a glue problem. The bookings live in one tool, the invoices in another, the customer messages in a third, and the glue between them is <em>you</em>, retyping things at 9pm. Every manual hand-off is a delay, a typo waiting to happen, and an hour you don't get back.</p>",
        "features": [
            ("Email & notification automation", "The right message to the right person at the right moment — confirmations, reminders, internal alerts — without anyone remembering to send them."),
            ("Reports that build themselves", "Weekly numbers pulled from your tools and delivered to your inbox or WhatsApp, already summarised in plain English."),
            ("Document generation", "Quotes, invoices and onboarding packs generated from a form entry or CRM record in seconds, in your template."),
            ("Data processing", "Spreadsheet wrangling, list cleaning, enquiry triage — the repetitive middle of your week, handled."),
            ("Internal workflows on n8n", "Built on open tooling you can inspect, hosted with GDPR in mind. If we ever part ways, the system stays yours."),
            ("Human approval gates", "Anything customer-facing waits for a human yes. Automation does the volume; you keep the wheel."),
        ],
        "wf_title": "Example: an enquiry becomes a booked job",
        "workflow": [
            "Customer fills in your website form at 9pm",
            "AI reads it, qualifies it and drafts a reply in your tone",
            "The details land in your CRM and you get a WhatsApp alert",
            "You tap approve — the reply and a booking link go out in under a minute",
            "Follow-ups run on day 1, 3 and 7 until they answer",
        ],
        "note": "<b>Honest note:</b> if you only have one repetitive task, you don't need us — a free Zapier or n8n account and an afternoon will do it. We earn our fee when there are five processes, customer data involved, and no time to babysit any of it.",
        "cta_h": "Find your most automatable hour",
        "cta_p": "Book a free 15-minute strategy call. We'll map your weekly grind and tell you honestly which parts are worth automating — even if you build it yourself.",
    },
    {
        "slug": "ai-lead-response",
        "nav": "AI lead response",
        "meta_title": "AI Lead Response System — 60-Second Replies | Firstreply",
        "meta_desc": "Every enquiry answered in under 60 seconds: AI-drafted, human-approved, followed up automatically. Stop losing the leads you already paid for.",
        "eyebrow": "Service · AI lead response system",
        "h1": "You're paying for leads. Then losing them.",
        "intro": "Someone fills in your form at 9pm and hears back at 11am — after they've booked your competitor. Our speed-to-lead system answers every enquiry in under 60 seconds, in your voice, with your thumb on the approve button.",
        "problem": "<p>The maths of lead response is brutal: the odds of reaching an enquiry collapse within the first hour, and the first business to reply usually wins the job — not the best one, the first one. Meanwhile your enquiries arrive exactly when you're busiest: evenings, weekends, mid-service. It isn't a discipline problem. It's a systems problem wearing a discipline costume.</p>",
        "features": [
            ("Instant capture, every source", "Website forms, Meta lead ads, email — everything lands in one pipeline the second it arrives."),
            ("AI drafts in your tone", "A reply written the way you actually write, ready within seconds of the enquiry landing."),
            ("One-tap human approval", "You get the draft on WhatsApp. Tap ✓ and it sends. Nothing reaches a customer without you."),
            ("Automated follow-up", "Polite nudges on a schedule until they answer — the touches nobody sends consistently by hand."),
            ("Appointment booking", "Replies carry your booking link, so hot leads convert themselves into calendar slots."),
            ("CRM updates included", "Every enquiry, reply and outcome logged without anyone typing it in."),
        ],
        "wf_title": "The 60-second journey",
        "workflow": [
            "New lead enquires — Saturday, 21:47",
            "Captured instantly into the pipeline",
            "AI drafts the reply in your tone (15 seconds)",
            "You approve with one tap on WhatsApp",
            "Reply delivered — 58 seconds after the enquiry",
        ],
        "note": "<b>Honest note:</b> you can start manually this week — turn on instant notifications, pre-write your first reply, decide your follow-up days. Our system is those fixes made automatic, for when volume outgrows willpower. Real result from our founding client Diji Catering: first-response time went from 4 hours to 60 seconds.",
        "cta_h": "Find out where your leads are leaking",
        "cta_p": "Book a free 15-minute Lead Leak Audit. We'll look at your ads, forms and inbox together and show you exactly where enquiries go cold.",
    },
    {
        "slug": "ai-voice-agents",
        "nav": "AI voice agents",
        "meta_title": "AI Voice Agents — 24/7 AI Answering Service | Firstreply",
        "meta_desc": "A professional 24/7 AI answering service for your business phone: enquiries handled, bookings taken, lead details captured, summaries sent to WhatsApp.",
        "eyebrow": "Service · AI voice agents",
        "h1": "Every missed call is a customer choosing whoever answers.",
        "intro": "You can't take calls mid-service, on a ladder, or at 11pm. An AI voice agent can — politely answering, capturing the details, booking the appointment, and sending you a summary before the customer has put their phone down.",
        "problem": "<p>Ring any five local businesses on a weekday afternoon and most won't pick up — they're doing the actual work. The caller doesn't leave a voicemail; they ring the next result on Google. Those calls never show up in any report, which is why the leak feels invisible. It isn't small.</p>",
        "features": [
            ("24/7 answering", "Every call answered in seconds, around the clock — including the Saturday-night enquiry worth the most."),
            ("Natural enquiry handling", "Answers your common questions — prices, availability, directions — from a script you approve."),
            ("Bookings by phone", "Checks availability and books appointments straight into your calendar."),
            ("Lead capture", "Name, number, what they need — collected and logged in your CRM, never on a sticky note."),
            ("Call summaries to WhatsApp", "Every call summarised and sent to you instantly, with a flag on the urgent ones."),
            ("Human handoff", "Anything complex or sensitive gets routed to you — the agent knows its limits."),
        ],
        "wf_title": "Example: the missed call that isn't",
        "workflow": [
            "Customer calls while you're mid-job — no answer possible",
            "AI voice agent picks up within two rings",
            "It answers their questions and collects their details",
            "A follow-up message with your booking link goes to the caller",
            "You get the summary on WhatsApp — lead recovered, not lost",
        ],
        "note": "<b>Honest note:</b> voice AI has limits. It's excellent at enquiries, availability and bookings; it should never negotiate, handle complaints or pretend to be human. We configure it to say it's an assistant, and to pass anything delicate to you.",
        "cta_h": "Hear what your callers would hear",
        "cta_p": "Book a free 15-minute strategy call and we'll walk through exactly how a voice agent would answer for your business — scripts, limits and all.",
    },
    {
        "slug": "ai-chatbots",
        "nav": "AI chatbots",
        "meta_title": "AI Chatbots for Business — Web & WhatsApp | Firstreply",
        "meta_desc": "AI chatbots for your website, WhatsApp, Messenger and Instagram: instant answers, lead capture and bookings — with human approval where it matters.",
        "eyebrow": "Service · AI chatbots",
        "h1": "Your customers message at midnight. Your reply shouldn't wait for morning.",
        "intro": "Website chat, WhatsApp, Messenger, Instagram DMs — your customers already live there. We build chatbots that answer instantly, capture the lead, and know exactly when to hand over to a human.",
        "problem": "<p>People don't ring businesses the way they used to — they message. And a message feels answered-or-ignored within minutes, not hours. If your Instagram DMs sit unread until Sunday evening, they might as well not exist. The channel shift already happened; most businesses' reply habits haven't.</p>",
        "features": [
            ("Website chat", "Answers questions, qualifies leads and books calls right on your site — 24/7."),
            ("WhatsApp automation", "The channel your customers actually prefer, answered instantly and GDPR-safely."),
            ("Messenger & Instagram DMs", "Comments and DMs from your ads answered while the interest is hot."),
            ("Trained on your business", "Your menu, your prices, your policies — not generic waffle."),
            ("Lead capture built in", "Every conversation becomes a contact with context in your CRM."),
            ("Human handover rules", "Complaints, complex quotes and VIPs get routed to a person, every time."),
        ],
        "wf_title": "Example: from ad comment to booked call",
        "workflow": [
            "Someone comments \"price?\" on your Facebook ad",
            "The bot replies in DM within seconds with the key details",
            "It asks the two qualifying questions you always ask",
            "Qualified lead lands in your CRM with the full conversation",
            "Your booking link goes out — or you step in personally for big jobs",
        ],
        "note": "<b>Try one right now:</b> the assistant in the corner of this page is a small scripted example — tap it and ask about pricing. <b>Honest note:</b> a chatbot that pretends to be human, or answers questions it doesn't know, damages trust faster than slow replies ever did. Ours introduce themselves as assistants, stick to what they know, and escalate the rest.",
        "cta_h": "Put an assistant in your DMs",
        "cta_p": "Book a free 15-minute strategy call. Bring your most-repeated customer question — we'll show you how the bot would handle it.",
    },
    {
        "slug": "lead-generation",
        "nav": "Lead generation & paid ads",
        "meta_title": "Lead Generation Agency — Meta & Google Ads | Firstreply",
        "meta_desc": "We don't just automate leads — we generate them. Meta and Google ads, landing pages, funnels and honest server-side tracking.",
        "eyebrow": "Service · Lead generation & paid marketing",
        "h1": "We don't just automate your leads. We generate them.",
        "intro": "Ads run by a marketer with 5+ years of hands-on Meta experience, landing pages built to convert, and tracking that tells you the truth about every pound — connected straight into the automation that answers each lead in 60 seconds.",
        "problem": "<p>Most agencies sell you clicks and call it success. But clicks aren't customers — and since iOS 14 broke pixel tracking, plenty of ad accounts are optimising on data that's simply wrong. You end up paying more for worse leads and can't prove which ads actually work. Fixing the pipe comes before pouring more money through it.</p>",
        "features": [
            ("Meta ads (Facebook & Instagram)", "Campaigns aimed at enquiries and bookings, not vanity clicks — 5+ years of hands-on experience."),
            ("Google Ads", "Capture the people already searching for what you do, in the moments that matter."),
            ("Landing pages & funnels", "Fast, focused pages built to convert — like the one you're reading."),
            ("Server-side conversion tracking", "Meta Conversions API set up properly, with event deduplication, so the algorithm learns from truth."),
            ("Email & follow-up marketing", "The leads you already have are the cheapest ones — nurture sequences that actually run."),
            ("Reporting that means something", "Spend → leads → replies → bookings, weekly, automatically. No 47-page PDF."),
        ],
        "wf_title": "The full funnel we build",
        "workflow": [
            "Advert reaches the right local audience",
            "Landing page converts the click into an enquiry",
            "AI answers in under 60 seconds, you approve",
            "CRM tracks every lead; follow-ups run on schedule",
            "Weekly report shows exactly what each booking cost",
        ],
        "note": "<b>Track record:</b> the founder has managed £22k+ of ad spend producing 5,500+ leads across education and design businesses, at £3.75–£5 per lead, with ~90% of ads rated high-performing — <a href=\"/case-studies\">numbers here</a>. <b>Honest note:</b> ads can't fix a weak offer, and we'll say so on the first call rather than take the retainer. And if your ad account's tracking is broken, we fix that first — it's a one-off job (£800–£1,200), not a subscription.",
        "cta_h": "Make every pound traceable",
        "cta_p": "Book a free 15-minute strategy call. We'll look at your ad account together and show you what's working, what isn't, and what it's really costing per booked customer.",
    },
    {
        "slug": "crm-automation",
        "nav": "CRM automation",
        "meta_title": "CRM Automation Services — Pipelines That Run | Firstreply",
        "meta_desc": "CRM automation for small businesses: pipelines that update themselves, lead scoring, follow-up triggers and reporting — HubSpot, Pipedrive or your stack.",
        "eyebrow": "Service · CRM automation",
        "h1": "Your CRM isn't the problem. Nobody updating it is.",
        "intro": "A CRM only works if the data goes in — and busy teams never have time to type it. We automate the updating, the scoring, the follow-up triggers and the reporting, so your pipeline finally reflects reality.",
        "problem": "<p>Every business buys a CRM with good intentions. Six months later it's a graveyard of half-filled records, and the real pipeline lives in the owner's head. The fix isn't more discipline or a different CRM — it's removing the typing altogether. When updates happen automatically, the CRM becomes what it was supposed to be: the one screen that tells you the truth.</p>",
        "features": [
            ("Automatic record creation", "Every enquiry from every channel becomes a contact with full context — no manual entry."),
            ("Pipeline stage automation", "Deals move themselves when things happen: reply received, call booked, quote sent."),
            ("Lead scoring", "Hot leads float to the top based on behaviour, so your attention goes where the money is."),
            ("Follow-up triggers", "No activity for 3 days? The nudge sends itself and the task appears — before the lead goes cold."),
            ("Works with your stack", "HubSpot, Pipedrive, or the spreadsheet you secretly still use — we automate what you have."),
            ("Self-building reports", "Pipeline value, conversion rates and response times, delivered weekly without anyone compiling them."),
        ],
        "wf_title": "Example: a deal that manages itself",
        "workflow": [
            "Enquiry arrives — contact and deal created automatically",
            "AI reply sent (human-approved) — deal moves to 'Contacted'",
            "Customer books a call — stage updates, prep note lands in your inbox",
            "Quote sent — follow-up sequence arms itself",
            "Deal won or lost — the numbers update your weekly report",
        ],
        "note": "<b>Honest note:</b> if you have fewer than ~20 enquiries a month, a well-kept spreadsheet beats a CRM — and we'll tell you so. CRM automation earns its keep when volume makes memory unreliable.",
        "cta_h": "Make your pipeline tell the truth",
        "cta_p": "Book a free 15-minute strategy call. We'll look at how leads flow through your business today and show you which updates should never be typed again.",
    },
]

SERVICES += [
    {
        "slug": "marketing-automation",
        "nav": "Marketing automation",
        "meta_title": "Marketing Automation Services UK | Firstreply",
        "meta_desc": "Marketing automation for UK and worldwide businesses: nurture sequences, review requests, seasonal campaigns and enquiry recovery that run themselves.",
        "eyebrow": "Service · Marketing automation",
        "h1": "Your marketing shouldn't stop when you go home.",
        "intro": "The follow-up email you meant to send, the review you meant to ask for, the Christmas campaign you started in December — marketing automation is those jobs done properly, on schedule, without you. We design the sequences; they run forever.",
        "problem": "<p>Most small-business marketing fails for one unglamorous reason: inconsistency. The newsletter goes out three times and stops. Past customers never hear from you again — even though they're the cheapest sales you'll ever make. It isn't a creativity problem. It's that marketing keeps losing the daily fight against actual work. Automation removes the fight.</p>",
        "features": [
            ("Nurture sequences", "Enquiries that didn't buy yet get a genuinely useful email series until they're ready — written once, sent forever."),
            ("Review & referral requests", "Every happy customer asked for a Google review or a referral at the right moment, automatically."),
            ("Past-customer reactivation", "Last year's clients invited back this year — the highest-ROI email most businesses never send."),
            ("Seasonal campaigns on rails", "Christmas parties pitched in October, summer season in March — planned once, fired on schedule."),
            ("Enquiry recovery", "Quotes gone quiet and abandoned enquiries politely re-engaged before they're lost for good."),
            ("Plain-English reporting", "Which sequences make money and which don't — weekly, automatic, honest."),
        ],
        "wf_title": "Example: the customer you'd have forgotten",
        "workflow": [
            "Wedding client's event completes in June",
            "Review request goes out three days later — five stars collected",
            "In January, the anniversary sequence offers a celebration menu",
            "She enquires again; AI answers in 60 seconds",
            "Repeat booking, zero marketing effort spent",
        ],
        "note": "<b>Honest note:</b> automation amplifies whatever you feed it. If the offer's weak or the list is cold, sequences won't save it — and we'll say so before building anything. Start with one sequence (review requests), prove it, then grow.",
        "cta_h": "Set the marketing running",
        "cta_p": "Book a free 15-minute strategy call. We'll find the one automated sequence that would pay for itself fastest in your business.",
    },
    {
        "slug": "n8n-automation",
        "nav": "n8n automation services",
        "meta_title": "n8n Automation Services — Built & Managed | Firstreply",
        "meta_desc": "n8n workflows designed, built and managed by a specialist who runs his own business on them. GDPR-first architecture, AI integrations, full handover.",
        "eyebrow": "Service · n8n automation services",
        "h1": "n8n workflows, built by someone who runs his own business on them.",
        "intro": "n8n is the open-source automation engine behind everything we build — powerful, private and yours to keep. If you want workflows designed properly, existing ones rescued, or AI wired into your stack, this is our native language.",
        "problem": "<p>n8n's power is also its trap: anyone can drag nodes together, so businesses end up with fragile workflows nobody documented, running on a laptop under someone's desk, quietly handling customer data with no thought for GDPR. Then the person who built it leaves. Automation you depend on deserves the same seriousness as any other infrastructure.</p>",
        "features": [
            ("Workflow design & build", "From a process description to a tested, documented workflow — including the error handling everyone skips."),
            ("AI integrations", "Claude and other AI models wired into your workflows for drafting, classifying and summarising — with human approval gates."),
            ("Self-hosted or cloud setup", "Proper hosting with backups, credentials stored safely, and updates that don't break things."),
            ("GDPR-first architecture", "Data minimisation by design — built by a founder with an MSc in Computer Network & System Security."),
            ("Rescue & refactor", "Inherited a mystery workflow that breaks monthly? We untangle, document and stabilise it."),
            ("Monitoring & handover", "Alerts when something fails, documentation you can read, and full ownership transferred to you."),
        ],
        "wf_title": "How an engagement runs",
        "workflow": [
            "Free call: we map the process you want automated",
            "Fixed quote — scope, timeline and what 'done' means",
            "Build and test, with your approval on every customer-facing step",
            "Documentation and handover — you own the workflows",
            "Optional monitoring plan keeps it healthy from £250/month",
        ],
        "note": "<b>Honest note:</b> n8n is open source and genuinely learnable — if you have one simple workflow and some patience, build it yourself (their docs are good). Hire us when it touches customer data, when downtime costs money, or when your time is worth more than the learning curve.",
        "cta_h": "Get your workflows built properly",
        "cta_p": "Book a free 15-minute strategy call. Describe the process; we'll tell you what it takes to automate — even if the answer is 'do it yourself, here's how'.",
    },
]

INDUSTRIES = [
    {
        "slug": "restaurants",
        "nav": "Restaurants & catering",
        "meta_title": "AI Automation for Restaurants & Caterers | Firstreply",
        "meta_desc": "AI booking assistant, instant enquiry replies, review requests and marketing automation for restaurants and caterers — proven with a live London client.",
        "eyebrow": "Industry · Restaurants, catering & hospitality",
        "h1": "Enquiries peak when you're mid-service. Exactly when nobody can answer.",
        "intro": "Bookings, event enquiries and \"do you have a table tonight?\" messages arrive at your busiest hours. We build systems that answer in seconds — so the Saturday-night enquiry doesn't become Monday's apology. This is our home turf: our founding client is a London caterer.",
        "problem": "<p>Hospitality has the cruellest enquiry timing of any industry: the moment someone wants to spend money with you is the moment you're physically unable to reply. A wedding enquiry at 9pm Saturday waits twelve hours minimum — and brides enquire with five caterers at once. First proper reply usually wins the tasting.</p>",
        "features": [
            ("AI booking & enquiry assistant", "Table requests, event enquiries and menu questions answered instantly on web, WhatsApp and social."),
            ("60-second event-lead replies", "Big-ticket catering and events enquiries get a personal-sounding reply while interest is hot — you approve each one."),
            ("Review requests on autopilot", "Happy guests asked for a Google review at the right moment, automatically."),
            ("Seasonal marketing automation", "Christmas parties pitched in October, wedding season in January — sequences that run themselves."),
            ("Missed-call recovery", "Can't pick up mid-service? The caller gets an instant text with your booking link."),
            ("Owner alerts on WhatsApp", "The enquiries worth interrupting service for, flagged to your pocket."),
        ],
        "wf_title": "A Saturday night, fixed",
        "workflow": [
            "21:47 — wedding enquiry for 80 guests lands via your website",
            "AI drafts a warm reply with sample menus attached",
            "You approve with one tap between courses",
            "Reply delivered 58 seconds after the enquiry",
            "Follow-ups run Tuesday and Friday until she books the tasting",
        ],
        "note": "<b>Real result:</b> our founding client, Diji Catering in London, went from a 4-hour average first response to 60 seconds — with every reply human-approved. That's the only case study on this site because it's the only one that's real. Yours could be next.",
        "cta_h": "Stop losing the Saturday-night enquiries",
        "cta_p": "Book a free 15-minute Lead Leak Audit. We'll look at your enquiry flow and show you exactly where hungry customers give up and book elsewhere.",
    },
    {
        "slug": "construction",
        "nav": "Construction & trades",
        "meta_title": "AI Automation for Construction & Trades | Firstreply",
        "meta_desc": "Quote automation, lead qualification and follow-up for builders and trades. Answer every enquiry from the scaffold — without putting the drill down.",
        "eyebrow": "Industry · Construction & trades",
        "h1": "You can't answer the phone from a scaffold. You don't have to.",
        "intro": "Every missed call while you're on the tools is a job going to the next builder on Google. We build systems that answer, qualify and follow up your enquiries — so the pipeline fills while you work.",
        "problem": "<p>Trades have a brutal catch-22: do the work and miss the calls, or take the calls and miss the deadline. Add quote-chasing — writing them at 10pm, then never finding time to follow up — and it's no mystery why feast-and-famine cycles happen. The enquiries were there; nobody was free to catch them.</p>",
        "features": [
            ("Missed-call rescue", "Can't pick up? The caller instantly gets a text: \"On site right now — tell me about your job here.\" Lead saved."),
            ("Lead qualification", "The AI asks what you'd ask: job type, location, timeline, budget signals — so you only ring the serious ones."),
            ("Quote follow-up automation", "Every quote chased on day 2, 7 and 14, politely, automatically. The jobs you've already priced stop going quiet."),
            ("Photo-first enquiries", "Customers send photos of the job on WhatsApp; you quote from the van."),
            ("Review requests", "Finished job → automatic Google review request while the customer's still delighted."),
            ("Diary protection", "Site visits booked into slots you choose — no more calls during the concrete pour."),
        ],
        "wf_title": "From missed call to booked site visit",
        "workflow": [
            "Call comes in while you're on the roof — missed",
            "Instant text goes to the caller with a job-details link",
            "They describe the job and send photos",
            "AI qualifies it and books a site visit into your free slot",
            "Quote sent later — follow-ups chase it so you don't have to",
        ],
        "note": "<b>Honest note:</b> the cheapest fix in construction is just following up your existing quotes — most firms never chase past one attempt. Start there manually this week. When volume makes that impossible, that's where we come in.",
        "cta_h": "Catch the jobs you're currently missing",
        "cta_p": "Book a free 15-minute strategy call. Bring last month's enquiry list — we'll show you how many jobs leaked and what a catch-all system looks like.",
    },
    {
        "slug": "estate-agents",
        "nav": "Estate agents",
        "meta_title": "AI Automation for Estate Agents | Firstreply",
        "meta_desc": "Instant property-enquiry replies, viewing bookings and lead nurturing for estate agents. Answer portal leads in seconds, not hours.",
        "eyebrow": "Industry · Estate & letting agents",
        "h1": "The buyer enquired about three houses. The fastest agent gets the viewing.",
        "intro": "Portal enquiries go to every agent with a matching listing. We make sure yours answers first — in seconds — then books the viewing, nurtures the chain, and keeps your pipeline warm automatically.",
        "problem": "<p>Property enquiries have a shelf life measured in minutes: a motivated buyer fires off five enquiries in one evening and books viewings with whoever responds. Meanwhile your negotiators are on viewings all day — physically unable to answer the very messages that feed next week's diary. Speed isn't a nice-to-have in this industry; it's the whole game.</p>",
        "features": [
            ("Instant portal-lead replies", "Rightmove and Zoopla enquiries answered in under a minute, any hour, with human approval."),
            ("Viewing bookings", "Qualified applicants offered real slots straight into negotiators' diaries."),
            ("Applicant qualification", "Position, finance, timeline — asked automatically, so viewings go to buyers who can proceed."),
            ("Valuation lead nurturing", "Homeowners thinking of selling get a warm sequence until they're ready — not one call and silence."),
            ("Vendor updates", "Weekly activity summaries to your vendors, compiled and sent automatically."),
            ("After-hours coverage", "The 9pm browser gets the same service as the 9am caller."),
        ],
        "wf_title": "From portal ping to booked viewing",
        "workflow": [
            "Enquiry lands from the portal at 20:40",
            "AI replies in seconds with answers and viewing slots",
            "Applicant picks a slot; qualification questions asked",
            "Viewing lands in the negotiator's diary with full context",
            "No-reply enquiries get nurtured for 14 days automatically",
        ],
        "note": "<b>Honest note:</b> AI should never negotiate offers or give financial advice — ours doesn't. It does the speed and the admin; your negotiators do the negotiating, with fuller diaries.",
        "cta_h": "Answer first. Win the viewing.",
        "cta_p": "Book a free 15-minute strategy call. We'll time your current enquiry response against your local rivals — the result usually decides the meeting by itself.",
    },
    {
        "slug": "dentists",
        "nav": "Dentists & clinics",
        "meta_title": "AI Automation for Dental Practices & Clinics | Firstreply",
        "meta_desc": "Appointment booking, reminder automation and patient communication for dental practices — fewer no-shows, fuller books, GDPR-first by design.",
        "eyebrow": "Industry · Dentists & private clinics",
        "h1": "Your reception can't answer two phones and a patient at once.",
        "intro": "New-patient enquiries, appointment changes and \"do you take my insurance?\" questions — all landing on a front desk that's already busy with the humans in the room. We automate the routine so your team can look up.",
        "problem": "<p>A dental practice loses money in quiet, predictable ways: the new-patient enquiry that rang during a busy clinic and never rang back; the Tuesday 3pm slot that a no-show turned into dead time; the hygiene recalls nobody had time to chase. None of it needs more staff. It needs the routine taken off their hands — carefully, because this is health data.</p>",
        "features": [
            ("Online appointment booking", "New and existing patients book into real slots, 24/7, without holding the line."),
            ("Reminder automation", "SMS/WhatsApp reminders at 7 days, 48 hours and on the morning — the proven no-show killer."),
            ("New-patient enquiry replies", "Price, insurance and availability questions answered instantly, with a booking link attached."),
            ("Recall automation", "Six-month check-up and hygiene recalls that actually go out, on schedule."),
            ("Waiting-list backfill", "A cancellation triggers offers to the waiting list — dead slots refilled automatically."),
            ("GDPR-first by design", "Health data handled with data minimisation and proper consent. Our founder's MSc is in exactly this."),
        ],
        "wf_title": "A cancellation, recovered in minutes",
        "workflow": [
            "Patient cancels tomorrow's 3pm by text",
            "The slot opens and the waiting list is messaged automatically",
            "First to accept books in; confirmation and directions sent",
            "Reminder goes out on the morning",
            "Your book stays full — nobody at the desk lifted a finger",
        ],
        "note": "<b>Honest note:</b> clinical questions belong with clinicians — our systems never give medical advice and route anything clinical to your team. We automate the diary and the chasing, not the dentistry.",
        "cta_h": "Fill the quiet slots",
        "cta_p": "Book a free 15-minute strategy call. We'll estimate what no-shows and missed enquiries cost your practice monthly — the number tends to fund the fix.",
    },
    {
        "slug": "education",
        "nav": "Education & training",
        "meta_title": "AI Automation for Education Consultancies | Firstreply",
        "meta_desc": "Enquiry response, consultation booking and enrolment follow-up automation for education consultancies, institutes and tutoring centres — worldwide.",
        "eyebrow": "Industry · Education consultancies, institutes & tutoring",
        "h1": "Parents enquire at 9pm. Intake deadlines don't wait for office hours.",
        "intro": "Course enquiries, admission questions and \"is there still a place?\" messages arrive after work, after school, and often from another time zone. We build systems that answer in seconds and follow up for the whole decision cycle — so no student slips away between enquiry and enrolment.",
        "problem": "<p>Education has the longest sales cycle of any local business: a parent or student enquires months before committing, compares several providers, and decides slowly — then all at once when the deadline looms. Most institutes lose students not at the decision, but in the quiet weeks in between, when nobody followed up. Add evening-and-weekend enquiry timing (and international time zones for consultancies), and a 9-to-5 admin team never stood a chance.</p>",
        "features": [
            ("Instant enquiry replies", "Course details, fees, requirements and intake dates answered in seconds — evenings, weekends and every time zone."),
            ("Consultation booking", "Qualified enquiries book a call or campus visit straight into your advisers' calendars."),
            ("Enrolment follow-up sequences", "The long decision cycle nurtured automatically — useful check-ins from enquiry to enrolment, not one call and silence."),
            ("Deadline & intake reminders", "Application deadlines, document checklists and term dates chased politely, on schedule."),
            ("WhatsApp-first communication", "The channel students and parents actually use, answered automatically with human approval."),
            ("Extra-careful data handling", "Student data — often minors' data — handled GDPR-first, with data minimisation by design."),
        ],
        "wf_title": "From evening enquiry to enrolled student",
        "workflow": [
            "Parent enquires at 21:15 about the September intake",
            "AI answers the course questions and asks the key qualifiers",
            "Consultation booked into an adviser's calendar",
            "Document checklist and deadline reminders go out automatically",
            "Follow-ups continue until enrolment — nobody slips away in the quiet weeks",
        ],
        "note": "<b>We know this industry:</b> the founder has run lead generation for two UK education consultancies — 5,000+ leads from £20k of ad spend (<a href=\"/case-studies\">see the track record</a>). <b>Honest note:</b> choosing education is a personal, high-trust decision — AI should handle the logistics and the speed, never the advising. Our systems book the conversation; your counsellors have it. And where minors' data is involved, we design with extra care, not extra automation.",
        "cta_h": "Stop losing students between enquiry and enrolment",
        "cta_p": "Book a free 15-minute strategy call. We'll map your enquiry-to-enrolment journey and show you exactly where students go quiet — and how to keep them.",
    },
    {
        "slug": "recruitment",
        "nav": "Recruitment agencies",
        "meta_title": "AI Automation for Recruitment Agencies | Firstreply",
        "meta_desc": "Candidate screening, email automation and CRM workflows for recruiters. Respond to every applicant fast and keep both sides of the desk warm.",
        "eyebrow": "Industry · Recruitment agencies",
        "h1": "Great candidates are off the market in days. Your admin takes weeks.",
        "intro": "Recruitment is a speed business run on manual admin: CV triage, chase emails, interview scheduling, CRM updates. We automate the drudgery on both sides of the desk so consultants spend their day where fees come from — talking to people.",
        "problem": "<p>Every recruiter knows the maths: the best candidates get snapped up within days, while a hundred applications per role bury the good ones in triage. Meanwhile clients judge you on responsiveness, candidates ghost when updates go quiet, and the CRM is three weeks behind reality. The bottleneck isn't talent-spotting — it's throughput.</p>",
        "features": [
            ("Candidate screening", "Applications parsed and shortlisted against your criteria in minutes — every applicant acknowledged."),
            ("Interview scheduling", "The three-way calendar dance handled automatically, with reminders both sides."),
            ("Candidate nurturing", "Silver-medal candidates kept warm with genuine check-ins until the right role appears."),
            ("Client update automation", "Shortlist progress and interview feedback summaries sent before clients ask."),
            ("CRM workflows", "Every CV, note and stage-change logged without consultant typing time."),
            ("Fast-response placements", "New role in? Matching candidates messaged within minutes, not tomorrow."),
        ],
        "wf_title": "From application to interview, same day",
        "workflow": [
            "Role goes live — 80 applications arrive by lunch",
            "AI screens against your criteria; every applicant gets a reply",
            "Top matches flagged to the consultant with summaries",
            "Consultant approves the shortlist; interviews auto-scheduled",
            "CRM and the client update themselves",
        ],
        "note": "<b>Honest note:</b> screening automation must be fair and explainable — ours flags and ranks for a human decision, it never auto-rejects. You stay the recruiter; the machine does the paperwork.",
        "cta_h": "Give consultants their day back",
        "cta_p": "Book a free 15-minute strategy call. We'll map one role's journey through your agency and show you the hours a machine should be doing.",
    },
]
